import { ThemeVariables } from '../../@types/theme';

export default function ({ }: ThemeVariables) {
  return {
    logo: require('./assets/images/tom_light.png'),
    sparkles: {
      topLeft: require('./assets/images/sparkles-top-left.png'),
      hadith_bg: require('./assets/images/hadith_bg.png'),
      top: require('./assets/images/sparkles-top.png'),
      topRight: require('./assets/images/sparkles-top-right.png'),
      right: require('./assets/images/sparkles-right.png'),
      bottomRight: require('./assets/images/sparkles-bottom-right.png'),
      bottom: require('./assets/images/sparkles-bottom.png'),
      bottomLeft: require('./assets/images/sparkles-bottom-left.png'),
      logoo: require('./assets/images/logoo.png'),
      sp_bottom: require('./assets/images/sp_bottom.png'),
      sp_header: require('./assets/images/sp_header.png'),
      wave: require('./assets/images/wave.png'),
      bell_icon: require('./assets/images/bell_icon.png'),
      user: require('./assets/images/user.png'),
      case: require('./assets/images/case.png'),
      home: require('./assets/images/home.png'),
      user_fill: require('./assets/images/user_fill.png'),
      case_fill: require('./assets/images/case_fill.png'),
      home_fill: require('./assets/images/home_fill.png'),
      gg_dot: require('./assets/images/gg_dot.png'),
      male_av: require('./assets/images/male_av.png'),
      male: require('./assets/images/male.png'),
      female_av: require('./assets/images/female_av.png'),
      files: require('./assets/images/files.png'),
      certificate: require('./assets/images/certificate.png'),
      bell_noti: require('./assets/images/bell_noti.png'),
      wives: require('./assets/images/wives.png'),
      setting: require('./assets/images/setting.png'),
      manage_asset: require('./assets/images/manage_asset.png'),
      kid: require('./assets/images/kid.png'),
      sign_out: require('./assets/images/sign_out.png'),
      nic_logo: require('./assets/images/nic_logo.png'),
      lock: require('./assets/images/lock.png'),
      education: require('./assets/images/education.png'),
      work: require('./assets/images/work.png'),
      payment_bg: require('./assets/images/payment_bg.png'),
      Logo_w: require('./assets/images/Logo_w.png'),
      stc: require('./assets/images/stc.png'),
      card_a: require('./assets/images/card_a.png'),
      apple_pay: require('./assets/images/apple_pay.png'),
      checked: require('./assets/images/checked.png'),
      init_process: require('./assets/images/init_process.png'),
      carrd: require('./assets/images/carrd.png'),
      filelist: require('./assets/images/filelist.png'),
      bg_hades: require('./assets/images/bg_hades.jpg'),
      bg_loading: require('./assets/images/bg_loading.png'),
      invoicebg: require('./assets/images/invoicebg.png'),
      barcode: require('./assets/images/barcode.png'),
      empty: require('./assets/images/empty.png'),
      tick: require('./assets/images/tick.png'),
      female: require('./assets/images/female.png'),
    },
    icons: {
      colors: require('./assets/images/colorswatch.png'),
      send: require('./assets/images/send.png'),
      translate: require('./assets/images/translate.png'),
    },
  };
}
